[package]
name = "xproxy-reverse"
version.workspace = true
edition.workspace = true
description = "Reverse proxy crate for xproxy"
license.workspace = true

[lints]
workspace = true

[dependencies]
xproxy-core.workspace = true
matchit = "0.8"
arc-swap = "1.7"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12"] }
rustls-pemfile = "2"
webpki-roots = "0.26"
rustls-native-certs = "0.8"
tokio = { version = "1", features = ["sync", "rt", "macros"] }
