[package]
name = "xproxy-forward"
version.workspace = true
edition.workspace = true
description = "Forward proxy crate for xproxy"
license.workspace = true

[lints]
workspace = true

[dependencies]
xproxy-core.workspace = true
tokio = { version = "1", features = ["net", "io-util"] }
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client-legacy", "http1", "tokio"] }
http = "1"
http-body-util = "0.1"
bytes = "1"
base64 = "0.22"
